<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$route['default_controller'] = 'home';
$route['404_override'] = '';
$route['translate_uri_dashes'] = FALSE;
$route['post/report'] = 'post/report';
$route['post/report_comment'] = 'post/report_comment';
$route['post/toggle_like_comment/(:num)'] = 'post/toggle_like_comment/$1';
$route['post/(:any)/(:num)'] = 'post/index/$1/$2';
$route['user/get_user_posts_ajax'] = 'User/get_user_posts_ajax';
$route['user/get_follows_ajax'] = 'User/get_follows_ajax';
$route['user/toggle_follow'] = 'User/toggle_follow';
$route['user/report_user'] = 'User/report_user';
$route['user/block_user'] = 'User/block_user';
$route['user/unblock_user'] = 'User/unblock_user';
$route['search/search_ajax'] = 'search/search_ajax';
$route['search'] = 'search/index';
$route['user/(:any)'] = 'user/index/$1';
$route['notifications/get_notifications'] = 'notifications/get_notifications';
$route['notifications/get_unread_count'] = 'notifications/get_unread_count';
$route['notifications/mark_read'] = 'notifications/mark_read';
$route['race-hub'] = 'race/index';
$route['race/get_schedule'] = 'race/get_schedule';
$route['race/get_standings'] = 'race/get_standings';
$route['race/get_results/(:num)'] = 'race/get_results/$1';
$route['chat/room/(:any)'] = 'chat/room/$1';
$route['chat/send_message'] = 'chat/send_message';
$route['chat/pusher_auth'] = 'chat/pusher_auth';
$route['chat'] = 'chat/index';
$route['auth/forgot_password'] = 'auth/forgot_password';
$route['auth/send_reset_link'] = 'auth/send_reset_link';
$route['auth/reset_password/(:any)'] = 'auth/reset_password/$1';
$route['auth/update_password_process'] = 'auth/update_password_process';
